# Generated by Django 3.2 on 2022-04-11 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('cm', '0001_initial'), ('cm', '0002_auto_20220103_0816'), ('cm', '0003_auto_20220117_2151'), ('cm', '0004_auto_20220217_2323'), ('cm', '0005_alter_collection_file'), ('cm', '0006_alter_collection_file'), ('cm', '0007_alter_collection_file'), ('cm', '0008_alter_collection_file'), ('cm', '0009_alter_collection_file'), ('cm', '0010_auto_20220218_0642'), ('cm', '0011_auto_20220219_0515'), ('cm', '0012_alter_collection_file'), ('cm', '0013_alter_collection_updated'), ('cm', '0014_alter_collection_updated'), ('cm', '0015_alter_collection_updated'), ('cm', '0016_scripttracker'), ('cm', '0017_scripttracker_should_reload'), ('cm', '0018_auto_20220302_0541'), ('cm', '0019_rename_updated_locally_scripttracker_updated'), ('cm', '0020_collection_level'), ('cm', '0021_auto_20220304_0516'), ('cm', '0022_auto_20220304_0517'), ('cm', '0023_rename_collection_collitemfile'), ('cm', '0024_collitemfile_parent'), ('cm', '0025_alter_collitemfile_parent'), ('cm', '0026_collitemfile_grandparent'), ('cm', '0027_remove_collitemfile_grandparent'), ('cm', '0028_auto_20220322_2041'), ('cm', '0029_auto_20220403_0537')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keep_running', models.BooleanField()),
                ('currently_writing', models.BooleanField()),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CollItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('file', models.FilePathField(blank=True, null=True, path='/media/kavon/files/shared/langit/langit-desktop/src/media', recursive=True)),
                ('json', models.TextField(blank=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('level', models.CharField(default='collection', max_length=255)),
                ('parent', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Otherfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('file', models.FilePathField(path='/media/kavon/files/shared/langit/langit-desktop/src/media', recursive=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
